services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: YojanaConnect_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5433:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5

  web:
    build: .

    command: sh -c "python manage.py migrate && gunicorn yojanaconnect.wsgi:application --bind 0.0.0.0:8000"

    volumes:
      - media_volume:/app/media

    ports:
      - "8000:8000"

    environment:
      - SECRET_KEY=docker-dev-secret-key-change-in-production
      - DEBUG=True
      - DB_NAME=YojanaConnect_DB
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432

    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  media_volume: