# Generated by Django 6.1 on 2026-10-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_analytics_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenprofile',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='scheme',
            name='target_demographic',
            field=models.CharField(choices=[('general', 'General'), ('student', 'Student'), ('senior_citizen', 'Senior Citizen'), ('girl_child', 'Girl Child'), ('woman', 'Woman'), ('farmer', 'Farmer'), ('disabled', 'Person with Disability'), ('bpl', 'Below Poverty Line')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='scheme',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Leave blank if the scheme has no fixed end date', null=True),
        ),
        migrations.AddIndex(
            model_name='scheme',
            index=models.Index(fields=['target_demographic'], name='core_scheme_target__be078f_idx'),
        ),
    ]
