# Generated by Django 6.1 on 2026-10-07 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_analytics_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender'), ('other', 'Other')], default='other', max_length=15),
        ),
        migrations.AddField(
            model_name='eligibilitycriteria',
            name='criteria_group',
            field=models.PositiveIntegerField(default=1, help_text='Criteria within the same group are ANDed; different groups for a scheme are ORed.'),
        ),
        migrations.AddField(
            model_name='eligibilitycriteria',
            name='gender_required',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender'), ('other', 'Other')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='target_demographic',
            field=models.CharField(choices=[('student', 'Student'), ('senior_citizen', 'Senior Citizen'), ('girl_child', 'Girl Child'), ('woman', 'Woman'), ('farmer', 'Farmer'), ('disabled', 'Disabled'), ('bpl', 'BPL'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='scheme',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='scheme',
            index=models.Index(fields=['target_demographic'], name='core_scheme_target__be078f_idx'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='core.application'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_disputes', to=settings.AUTH_USER_MODEL),
        ),
    ]
